### ISSUE TITLE
如果不加这一行会报错

### ISSUE THREAD

**Issue by asjdf** [idoctype/newsToQzone#1]
我在29行后面加上这个就不报错了
`browser.switch_to.default_content()`
是不是由于改版然后代码没有更新呢？

**Comment by Yazzyk** [comment]
😂不太清楚，我写完跑过应该没什么问题。不过这个是很久以前写的了，我也记不清了

**Comment by Yazzyk** [comment]
> 我在29后面行加上这个就不报错了
> `browser.switch_to.default_content()`
> 的英文不是由于改版然后代码没有更新呢？

不对啊!29行是空白行啊

**Comment by asjdf** [comment]
emmm 反正加上去就对了

**Comment by asjdf** [comment]
如果不从内嵌的网页跳出来的话是无法进行下一步的操作的

**Comment by asjdf** [comment]
我的项目中借用了部分你的代码 并且加了一些冗余 虽然不完美 但是在网络环境较差的情况下运行得更好一点（对于我的环境来说

**Comment by Yazzyk** [comment]
好吧,我的代码也是借鉴的别人的,我对Python也不是很熟,当初不知道拿树莓派干嘛用的时候写的了
